import { StorageItem } from "./types";

export const MOCK_STORAGE_ITEMS: StorageItem[] = [
  {
    id: "1",
    type: "car",
    name: "Classic Mustang",
    make: "Ford",
    model: "Mustang GT",
    year: 1967,
    licensePlate: "ABC-1234",
    ownerName: "John Doe",
    ownerPhone: "(555) 123-4567",
    ownerEmail: "john@example.com",
    unitNumber: "A-101",
    status: "stored",
    lastAccessed: "2026-03-25",
    imageUrl: "https://picsum.photos/seed/mustang/800/600",
    notes: "Requires battery tender. Do not move without owner present.",
    insuranceExpiry: "2026-12-31"
  },
  {
    id: "2",
    type: "boat",
    name: "Sea Breeze",
    make: "Sea Ray",
    model: "Sundancer 260",
    year: 2022,
    hullId: "SRY12345A222",
    ownerName: "Jane Smith",
    ownerPhone: "(555) 987-6543",
    ownerEmail: "jane@example.com",
    unitNumber: "B-205",
    status: "stored",
    lastAccessed: "2026-03-28",
    imageUrl: "https://picsum.photos/seed/boat/800/600",
    notes: "Winterized. Cover is tightly secured.",
    insuranceExpiry: "2026-08-15"
  },
  {
    id: "3",
    type: "car",
    name: "Silver Porsche",
    make: "Porsche",
    model: "911 Carrera",
    year: 2021,
    licensePlate: "PRSH-911",
    ownerName: "Robert Brown",
    ownerPhone: "(555) 444-3333",
    ownerEmail: "robert@example.com",
    unitNumber: "A-105",
    status: "maintenance",
    lastAccessed: "2026-03-29",
    imageUrl: "https://picsum.photos/seed/porsche/800/600",
    notes: "Oil change and tire rotation in progress.",
    insuranceExpiry: "2026-11-01"
  },
  {
    id: "4",
    type: "boat",
    name: "Lake Cruiser",
    make: "Bayliner",
    model: "Element E18",
    year: 2019,
    hullId: "BAY98765B919",
    ownerName: "Alice Wilson",
    ownerPhone: "(555) 222-1111",
    ownerEmail: "alice@example.com",
    unitNumber: "B-210",
    status: "out",
    lastAccessed: "2026-03-30",
    imageUrl: "https://picsum.photos/seed/bayliner/800/600",
    notes: "Picked up for the weekend. Expected back Monday morning.",
    insuranceExpiry: "2027-01-20"
  }
];
